modLoader="javafml" #mandatory

loaderVersion="[33,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

issueTrackerURL="https://github.com/How-Bout-No/Outvoted/issues" #optional

[[mods]] #mandatory

modId="outvoted" #mandatory

version="${version}" #mandatory

displayName="Outvoted" #mandatory

#updateJSONURL="https://www.curseforge.com/minecraft/mc-mods/outvoted" #optional

displayURL="https://www.curseforge.com/minecraft/mc-mods/outvoted" #optional

logoFile="logo.png" #optional

credits="Curseforge Community, David2753/Lord_Noodal for contributions, Obi and Furti for textures" #optional

authors="HowBoutNo" #optional

description='Adds in mobs that got outvoted!'
#A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.outvoted]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.0.0-beta.8,)"
    ordering="NONE"
    side="BOTH"
